name: CI
on:
  push:
    branches:
      - dev
      - '**'
      - '!gh-pages'
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      ICARE_USER: ${{ secrets.ICARE_USER }}
      ICARE_PASSWORD: ${{ secrets.ICARE_PASSWORD }}
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - name: Run tests with custom commands
        env:
          JULIA_NUM_THREADS: 2
        shell: julia --project --color=yes {0}
        run: |
          using Pkg
          Pkg.rm("SFTP")
          Pkg.add(url="https://github.com/LIM-AeroCloud/SFTP.jl.git#main")
          Pkg.instantiate()
          Pkg.test()
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Configure doc environment
        shell: julia --project --color=yes {0}
        run: |
          using Pkg
          Pkg.rm("SFTP")
          Pkg.add(url="https://github.com/LIM-AeroCloud/SFTP.jl.git#main")
          Pkg.activate("docs")
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - name: Run doctests
        shell: julia --project=docs --color=yes {0}
        run: |
          using Documenter: DocMeta, doctest
          using ICARE
          DocMeta.setdocmeta!(ICARE, :DocTestSetup, :(using ICARE); recursive=true)
          doctest(ICARE)
